apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pr-{{.APPID}}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .REPO_URL }}
    targetRevision: HEAD
    path: helm

    helm:
      values: |
        image:
          repository: "{{ .DOCKER_REPO }}"
          tag: "{{ .IMAGE_TAG }}"
        ingress:
          host: "{{ .INGRESS_HOSTNAME }}.10.0.0.6.nip.io"

  destination:
    server: https://kubernetes.default.svc
    namespace: pr-{{.APPID}}

  # Sync policy
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).